version: '3'
services:
  core_api:
    build: .
    container_name:  "mcontainer"
    ports:
      - "8000:8080"

    volumes:
      - /app
      - /tests
      
  test_runner:
    build:
      context: .
    command: pytest tests/test_main.py
    volumes:
      - ./tests:/app/tests
    depends_on:
      - core_api