"""initial1

Revision ID: 0b8272d6b96c
Revises: 3630cc416cbc
Create Date: 2023-07-19 14:38:18.492776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8272d6b96c'
down_revision = '3630cc416cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
